<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net9.0-android;net9.0-ios;net9.0-maccatalyst;net9.0-windows10.0.19041.0</TargetFrameworks>

		<OutputType>Exe</OutputType>
		<RootNamespace>Valedourado</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<ApplicationTitle>Valedourado</ApplicationTitle>

		<ApplicationId>com.companyname.valedourado</ApplicationId>

		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

		<PublishDir>$(SolutionDir)publicacao-final\$(ProjectName)\</PublishDir>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tizen'">6.5</SupportedOSPlatformVersion>

		<DefaultLanguage>pt-br</DefaultLanguage>
		<WindowsPackageType>MSIX</WindowsPackageType>
		<PackageCertificateThumbprint>9E43E7A107DE27093692FEEED66A6CFA9859758A</PackageCertificateThumbprint>
		<AppxPackageSigningEnabled>True</AppxPackageSigningEnabled>
		<GenerateAppInstallerFile>False</GenerateAppInstallerFile>
		<AppxPackageSigningTimestampDigestAlgorithm>SHA256</AppxPackageSigningTimestampDigestAlgorithm>
		<AppxAutoIncrementPackageRevision>True</AppxAutoIncrementPackageRevision>
		<AppxSymbolPackageEnabled>True</AppxSymbolPackageEnabled>
		<GenerateTestArtifacts>True</GenerateTestArtifacts>
		<GenerateTemporaryStoreCertificate>True</GenerateTemporaryStoreCertificate>
		<HoursBetweenUpdateChecks>0</HoursBetweenUpdateChecks>
		<Platforms>AnyCPU;ARM32</Platforms>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net9.0-android|AnyCPU'">
	  <AndroidPackageFormat>apk</AndroidPackageFormat>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net9.0-android|ARM32'">
	  <AndroidPackageFormat>apk</AndroidPackageFormat>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Valedourado.Shared\Valedourado.Shared.csproj" />
	</ItemGroup>

	<ItemGroup>
		<MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#D94f05" BaseSize="59,25" ForegroundScale="0.65" />
		<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#D94f05" BaseSize="5462,2365" />
		<MauiImage Include="Resources\Images\*" />
		<MauiImage Update="Resources\Images\dotnet_bot.png" Resize="True" BaseSize="300,185" />
		<MauiFont Include="Resources\Fonts\*" />
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.HighPerformance" Version="8.4.0" />
		<PackageReference Include="CommunityToolkit.Maui" Version="12.2.0" />
		<PackageReference Include="CommunityToolkit.Maui.Core" Version="12.2.0" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="9.0.8" />
		<PackageReference Include="Microsoft.Maui.Controls" Version="9.0.90" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="9.0.8" />
	</ItemGroup>

	<ItemGroup>
		<MauiXaml Update="Resources\Styles\Colors.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Resources\Styles\Styles.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Resources\Styles\ValedouradoStyles.xaml">
			<Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\PaletizacaoOpSelectionPage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
		<MauiXaml Update="Views\PaletizacaoPage.xaml">
		  <Generator>MSBuild:Compile</Generator>
		</MauiXaml>
	</ItemGroup>

</Project>